# name: Check-URL

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   check:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check URL
#         uses: actions/checkout@v2

#       - name: Install dependencies
#         run: npm install

#       - name: Uncommented-Localhost-URL
#         run: |
#           if grep -q '// const URL = "http://localhost:3001"' src/URL.jsx; then
#             echo "Success: Found commented localhost URL in your code."
#             exit 0
#           else
#             exit 1
#           fi
